apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: factorial-java-function
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: hub.docker.com/smartinrub/factorial-java-function
            env:
            - name: TARGET
              value: "Factorial Java Function"
